# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-25 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garbage_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_category', models.CharField(default='', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Dot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('description', models.CharField(default='', max_length=120)),
                ('dot_x', models.FloatField(default=0.0)),
                ('dot_y', models.FloatField(default=0.0)),
                ('category', models.ManyToManyField(to='garbage_map.Category')),
            ],
        ),
    ]
