# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-24 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dots',
            old_name='dot_x',
            new_name='dot_y',
        ),
    ]
