# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-25 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0002_category_dot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_of_category',
            new_name='name',
        ),
    ]
