# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-24 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0002_auto_20190424_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='dots',
            name='dot_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dots',
            name='dot_y',
            field=models.FloatField(default=0.0),
        ),
    ]
