# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-25 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0003_auto_20190425_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dot',
            old_name='dot_x',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='dot',
            old_name='dot_y',
            new_name='y',
        ),
    ]
