# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-24 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0003_auto_20190424_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='dots',
            name='Subject',
            field=models.CharField(default='', max_length=120),
        ),
    ]
