# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-24 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0004_dots_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dots',
            new_name='Dot',
        ),
    ]
