# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-26 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0005_auto_20190426_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dot',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='\u0418\u043c\u044f'),
        ),
    ]
