# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-24 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0005_auto_20190424_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dot',
            old_name='Subject',
            new_name='subject',
        ),
    ]
