# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-26 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0006_auto_20190426_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='category',
            field=models.ManyToManyField(to='garbage_map.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u043c\u0443\u0441\u043e\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='description',
            field=models.CharField(default='', max_length=120, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0443\u043d\u043a\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='x',
            field=models.FloatField(default=0.0, verbose_name='\u041a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u0430 \u0445'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='y',
            field=models.FloatField(default=0.0, verbose_name='\u041a\u043e\u043e\u0440\u043f\u0434\u0438\u043d\u0430\u0442\u0430 \u0443'),
        ),
    ]
