# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-26 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0007_auto_20190426_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='dot',
            name='working_hours',
            field=models.TextField(default='', verbose_name='\u0412\u0440\u0435\u043c\u044f \u0438 \u0447\u0430\u0441\u044b \u0440\u0430\u0431\u043e\u0442\u044b'),
        ),
    ]
