# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-26 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0008_dot_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dot',
            name='y',
            field=models.FloatField(default=0.0, verbose_name='\u041a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u0430 \u0443'),
        ),
    ]
