# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-06 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0010_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dot',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo_garbage', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
