# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-07 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0011_dot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dot',
            name='x',
            field=models.FloatField(verbose_name='\u041a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u0430 \u0445'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='y',
            field=models.FloatField(verbose_name='\u041a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u0430 \u0443'),
        ),
    ]
