# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-08 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0012_auto_20190507_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dot',
            old_name='category',
            new_name='categories',
        ),
    ]
