# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-14 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0013_auto_20190508_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='dot',
            name='addres',
            field=models.CharField(default='', max_length=512, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
    ]
