# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-22 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0017_auto_20190522_0545'),
        ('garbage_map', '0015_auto_20190522_0443'),
    ]

    operations = [
    ]
