# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-05 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0019_category_name_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='dot',
            name='phone',
            field=models.CharField(default='', max_length=512, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='description',
            field=models.TextField(default='', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='name',
            field=models.CharField(default='', max_length=512, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0443\u043d\u043a\u0442\u0430'),
        ),
    ]
