# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-05 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_map', '0020_auto_20190605_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dot',
            name='phone',
            field=models.TextField(default='', verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
    ]
